name 'badgerious-npackd'
version '1.1.0'
summary 'Manages Npackd (a package manager for Windows) packages.'
description 'Manages Npackd (a package manager for Windows) packages.'
project_page 'https://github.com/badgerious/puppet-npackd'
license 'Apache License, Version 2.0'
author 'badgerious'
